// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Audit_Log", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AUDIT_LOG", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Venue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EVENT", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EventDate = new DateTime(2026, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Concierto de Rock",
                            Status = "Active",
                            Venue = "Estadio Unaj"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Reservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ReservedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SeatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SeatId");

                    b.HasIndex("UserId");

                    b.ToTable("RESERVATION", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Seat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RowIdentifier")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SeatNumber")
                        .HasColumnType("int");

                    b.Property<int>("SectorId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SectorId");

                    b.ToTable("SEAT", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            RowIdentifier = "A",
                            SeatNumber = 1,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            RowIdentifier = "A",
                            SeatNumber = 2,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            RowIdentifier = "A",
                            SeatNumber = 3,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            RowIdentifier = "A",
                            SeatNumber = 4,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            RowIdentifier = "A",
                            SeatNumber = 5,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000006"),
                            RowIdentifier = "A",
                            SeatNumber = 6,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000007"),
                            RowIdentifier = "A",
                            SeatNumber = 7,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000008"),
                            RowIdentifier = "A",
                            SeatNumber = 8,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000009"),
                            RowIdentifier = "A",
                            SeatNumber = 9,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000010"),
                            RowIdentifier = "A",
                            SeatNumber = 10,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000011"),
                            RowIdentifier = "A",
                            SeatNumber = 11,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000012"),
                            RowIdentifier = "A",
                            SeatNumber = 12,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000013"),
                            RowIdentifier = "A",
                            SeatNumber = 13,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000014"),
                            RowIdentifier = "A",
                            SeatNumber = 14,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000015"),
                            RowIdentifier = "A",
                            SeatNumber = 15,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000016"),
                            RowIdentifier = "A",
                            SeatNumber = 16,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000017"),
                            RowIdentifier = "A",
                            SeatNumber = 17,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000018"),
                            RowIdentifier = "A",
                            SeatNumber = 18,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000019"),
                            RowIdentifier = "A",
                            SeatNumber = 19,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000020"),
                            RowIdentifier = "A",
                            SeatNumber = 20,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000021"),
                            RowIdentifier = "A",
                            SeatNumber = 21,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000022"),
                            RowIdentifier = "A",
                            SeatNumber = 22,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000023"),
                            RowIdentifier = "A",
                            SeatNumber = 23,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000024"),
                            RowIdentifier = "A",
                            SeatNumber = 24,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000025"),
                            RowIdentifier = "A",
                            SeatNumber = 25,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000026"),
                            RowIdentifier = "A",
                            SeatNumber = 26,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000027"),
                            RowIdentifier = "A",
                            SeatNumber = 27,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000028"),
                            RowIdentifier = "A",
                            SeatNumber = 28,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000029"),
                            RowIdentifier = "A",
                            SeatNumber = 29,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000030"),
                            RowIdentifier = "A",
                            SeatNumber = 30,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000031"),
                            RowIdentifier = "A",
                            SeatNumber = 31,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000032"),
                            RowIdentifier = "A",
                            SeatNumber = 32,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000033"),
                            RowIdentifier = "A",
                            SeatNumber = 33,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000034"),
                            RowIdentifier = "A",
                            SeatNumber = 34,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000035"),
                            RowIdentifier = "A",
                            SeatNumber = 35,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000036"),
                            RowIdentifier = "A",
                            SeatNumber = 36,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000037"),
                            RowIdentifier = "A",
                            SeatNumber = 37,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000038"),
                            RowIdentifier = "A",
                            SeatNumber = 38,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000039"),
                            RowIdentifier = "A",
                            SeatNumber = 39,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000040"),
                            RowIdentifier = "A",
                            SeatNumber = 40,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000041"),
                            RowIdentifier = "A",
                            SeatNumber = 41,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000042"),
                            RowIdentifier = "A",
                            SeatNumber = 42,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000043"),
                            RowIdentifier = "A",
                            SeatNumber = 43,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000044"),
                            RowIdentifier = "A",
                            SeatNumber = 44,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000045"),
                            RowIdentifier = "A",
                            SeatNumber = 45,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000046"),
                            RowIdentifier = "A",
                            SeatNumber = 46,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000047"),
                            RowIdentifier = "A",
                            SeatNumber = 47,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000048"),
                            RowIdentifier = "A",
                            SeatNumber = 48,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000049"),
                            RowIdentifier = "A",
                            SeatNumber = 49,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000050"),
                            RowIdentifier = "A",
                            SeatNumber = 50,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000101"),
                            RowIdentifier = "B",
                            SeatNumber = 1,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000102"),
                            RowIdentifier = "B",
                            SeatNumber = 2,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000103"),
                            RowIdentifier = "B",
                            SeatNumber = 3,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000104"),
                            RowIdentifier = "B",
                            SeatNumber = 4,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000105"),
                            RowIdentifier = "B",
                            SeatNumber = 5,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000106"),
                            RowIdentifier = "B",
                            SeatNumber = 6,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000107"),
                            RowIdentifier = "B",
                            SeatNumber = 7,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000108"),
                            RowIdentifier = "B",
                            SeatNumber = 8,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000109"),
                            RowIdentifier = "B",
                            SeatNumber = 9,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000110"),
                            RowIdentifier = "B",
                            SeatNumber = 10,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000111"),
                            RowIdentifier = "B",
                            SeatNumber = 11,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000112"),
                            RowIdentifier = "B",
                            SeatNumber = 12,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000113"),
                            RowIdentifier = "B",
                            SeatNumber = 13,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000114"),
                            RowIdentifier = "B",
                            SeatNumber = 14,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000115"),
                            RowIdentifier = "B",
                            SeatNumber = 15,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000116"),
                            RowIdentifier = "B",
                            SeatNumber = 16,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000117"),
                            RowIdentifier = "B",
                            SeatNumber = 17,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000118"),
                            RowIdentifier = "B",
                            SeatNumber = 18,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000119"),
                            RowIdentifier = "B",
                            SeatNumber = 19,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000120"),
                            RowIdentifier = "B",
                            SeatNumber = 20,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000121"),
                            RowIdentifier = "B",
                            SeatNumber = 21,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000122"),
                            RowIdentifier = "B",
                            SeatNumber = 22,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000123"),
                            RowIdentifier = "B",
                            SeatNumber = 23,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000124"),
                            RowIdentifier = "B",
                            SeatNumber = 24,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000125"),
                            RowIdentifier = "B",
                            SeatNumber = 25,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000126"),
                            RowIdentifier = "B",
                            SeatNumber = 26,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000127"),
                            RowIdentifier = "B",
                            SeatNumber = 27,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000128"),
                            RowIdentifier = "B",
                            SeatNumber = 28,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000129"),
                            RowIdentifier = "B",
                            SeatNumber = 29,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000130"),
                            RowIdentifier = "B",
                            SeatNumber = 30,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000131"),
                            RowIdentifier = "B",
                            SeatNumber = 31,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000132"),
                            RowIdentifier = "B",
                            SeatNumber = 32,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000133"),
                            RowIdentifier = "B",
                            SeatNumber = 33,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000134"),
                            RowIdentifier = "B",
                            SeatNumber = 34,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000135"),
                            RowIdentifier = "B",
                            SeatNumber = 35,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000136"),
                            RowIdentifier = "B",
                            SeatNumber = 36,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000137"),
                            RowIdentifier = "B",
                            SeatNumber = 37,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000138"),
                            RowIdentifier = "B",
                            SeatNumber = 38,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000139"),
                            RowIdentifier = "B",
                            SeatNumber = 39,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000140"),
                            RowIdentifier = "B",
                            SeatNumber = 40,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000141"),
                            RowIdentifier = "B",
                            SeatNumber = 41,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000142"),
                            RowIdentifier = "B",
                            SeatNumber = 42,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000143"),
                            RowIdentifier = "B",
                            SeatNumber = 43,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000144"),
                            RowIdentifier = "B",
                            SeatNumber = 44,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000145"),
                            RowIdentifier = "B",
                            SeatNumber = 45,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000146"),
                            RowIdentifier = "B",
                            SeatNumber = 46,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000147"),
                            RowIdentifier = "B",
                            SeatNumber = 47,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000148"),
                            RowIdentifier = "B",
                            SeatNumber = 48,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000149"),
                            RowIdentifier = "B",
                            SeatNumber = 49,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000150"),
                            RowIdentifier = "B",
                            SeatNumber = 50,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        });
                });

            modelBuilder.Entity("Domain.Entities.Sector", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("SECTOR", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 50,
                            EventId = 1,
                            Name = "Platea Alta",
                            Price = 5000m
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 50,
                            EventId = 1,
                            Name = "Campo General",
                            Price = 3000m
                        });
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("USER", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "test@example.com",
                            Name = "Usuario Test",
                            PasswordHash = "hashed_password"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Audit_Log", b =>
                {
                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("Audit_Logs")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Reservation", b =>
                {
                    b.HasOne("Domain.Entities.Seat", "Seat")
                        .WithMany()
                        .HasForeignKey("SeatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("Reservations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Seat");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Seat", b =>
                {
                    b.HasOne("Domain.Entities.Sector", "Sector")
                        .WithMany("Seats")
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sector");
                });

            modelBuilder.Entity("Domain.Entities.Sector", b =>
                {
                    b.HasOne("Domain.Entities.Event", "Event")
                        .WithMany("Sectors")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("Domain.Entities.Event", b =>
                {
                    b.Navigation("Sectors");
                });

            modelBuilder.Entity("Domain.Entities.Sector", b =>
                {
                    b.Navigation("Seats");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Navigation("Audit_Logs");

                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
